name: NodeJS with Webpack

permissions:
  id-token: write
  pages: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Build
      run: |
        npm install
        npx webpack

    - uses: actions/upload-pages-artifact@v3
      with:
        path: "dist/"

    - uses: actions/deploy-pages@v4
